config/routes.rb
Rails.application.routes.draw do
  root   'static_pages#home'
  get    '/about',   to: 'static_pages#about'
  get    '/signup',  to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  # root -> ルートパス(localhost:3000)でアクセスした場合に割り当てられる設定で、Controllerファイルに記述するindexメソッドを実行するように定義
  get '/posts', to: 'posts#index'

  # 投稿ページを表示
  get '/posts/new', to: 'posts#new'
  resources :users
  resources :posts, only: [:create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  default_scope -> { order(created_at: :desc) }
  validates :user_id, presence: true
  validates :content, presence: true, length: { maximum: 140 }
  mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts, dependent: :destroy
  attr_accessor :remember_token
  before_save { self.email = email.downcase }
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: true
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true

  # 渡された文字列のハッシュ値を返す
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  # ランダムなトークンを返す
  def User.new_token
    SecureRandom.urlsafe_base64
  end

  # 永続セッションのためにユーザーをデータベースに記憶する
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  # 渡されたトークンがダイジェストと一致したらtrueを返す
  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  # ユーザーのログイン情報を破棄する
  def forget
    update_attribute(:remember_digest, nil)
  end

  def comment
    Post.where("user_id = ?", id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper

  private

    # ユーザーのログインを確認する
    def logged_in_user
      unless logged_in?
        store_location
        flash[:danger] = "ログインしてください"
        redirect_to login_url
      end
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :logged_in_user, only: [:create, :destroy]
  before_action :correct_user,   only: :destroy

  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      flash[:success] = "post created!"
      redirect_to root_url
    else
      render 'static_pages/home'
    end
  end

  def destroy
    @comment.destroy
    flash[:success] = "post deleted"
    redirect_to request.referrer || root_url
  end

  private

  def post_params
    params.require(:post).permit(:content, :image)
  end

  def correct_user
    @post = current_user.posts.find_by(id: params[:id])
    redirect_to root_url if @post.nil?
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    @user = User.find_by(email: params[:session][:email].downcase)
    if @user && @user.authenticate(params[:session][:password])
      #ユーザログイン後にユーザ情報のページヘリダイレクトする
      log_in @user
      #チェックされていたらユーザを記憶する
      params[:session][:remember_me] == '1' ? remember(@user) : forget(@user)
      redirect_back_or @user
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    log_out if logged_in? # ログイン中の場合のみログアウトする
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    if logged_in?
    @post = current_user.posts.build
    @comment_items = current_user.comment.paginate(page: params[:page])
    end
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:index, :edit, :update, :destroy]
  before_action :correct_user,   only: [:edit, :update]
  before_action :admin_user,     only: :destroy

  def index
    @users = User.paginate(page: params[:page])
  end

  def show
    @user = User.find(params[:id])
    @posts = @user.posts.paginate(page: params[:page])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "ようこそstarsへ！"
      redirect_to @user
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user.params)
      flash[:notice] = "編集が完了しました"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "削除されました"
    redirect_to users_url
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation)
    end

        # beforeアクション

    # ログイン済みユーザーかどうか確認
    def logged_in_user
      unless logged_in?
        store_location
        flash[:danger] = "まずはログインしてください"
        redirect_to login_url
      end
    end

    # 正しいユーザーかどうか確認
    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless @user == current_user
    end

    # 管理者かどうか確認
    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  #ページごとの完全なタイトルを返す
  def full_title(page_title = "")       # メソッド定義とオプション引数
    base_title = "stars"                # 変数への代入
    if page_title.empty?                # 論理値テスト
      base_title                        # 暗黙の戻り値
    else
      page_title + " | " + base_title  # 文字列の結合
    end
  end

end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  # 渡されたユーザーでログインする
  def log_in(user)
    session[:user_id] = user.id
  end

  # ユーザーのセッションを永続的にする
  def remember(user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end

  # 記憶トークンcookieに対応するユーザーを返す
  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    elsif (user_id = cookies.signed[:user_id])
      user = User.find_by(id: user_id)
      if user && user.authenticated?(cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end

  # ユーザーがログインしていればtrue、その他ならfalseを返す
  def logged_in?
    !current_user.nil?
  end

  # 永続的セッションを破棄する
  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end

  # 現在のユーザーをログアウトする
  def log_out
    forget(current_user)
    session.delete(:user_id)
    @current_user = nil
  end

    # 記憶したURL（もしくはデフォルト値）にリダイレクト
    def redirect_back_or(default)
      redirect_to(session[:forwarding_url] || default)
      session.delete(:forwarding_url)
    end

    # アクセスしようとしたURLを覚えておく
    def store_location
      session[:forwarding_url] = request.original_url if request.get?
    end
  end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper

  # 引数で与えられたユーザーのGravatar画像を返す
  def gravatar_for(user, size: 100)
    gravatar_id  = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    記事投稿サイト
  </small>
  <nav>
    <ul>
      <li><%= link_to "About", about_path, id: "btn-bottom" %>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
  <div class="container", style="background-color: #8C5305;">

    <div class="navbar-header">

      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>

      <%= link_to "stars", root_path, id: "logo" %>
    </div>

    <nav>
      <ul class="nav navbar-nav navbar-expand-sm navbar-right navbar-collapse collapse">
        <li><%= link_to "ホーム", root_path, id: "navbar" %></li>
        <% if logged_in? %>
          <li><%= link_to "ユーザー一覧", users_path, id: "navbar" %></li>
          <li class="dropdown">
            <button type="button" id="dropdown1"
      class="btn btn-secondary dropdown-toggle
      btn-lg"
      data-toggle="dropdown"
      aria-haspopup="true"
      aria-expanded="false">
              アカウント <b class="caret"></b>
            </button>
            <ul class="dropdown-menu" role="menu">
              <li><%= link_to "プロフィール", current_user %></li>
              <li class="divider"></li>
              <li><%= link_to "編集", edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "ログアウト", logout_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "ログイン", login_path, id: "navbar" %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container">
    <% flash.each do |message_type, message| %>
    <!-- <div class="alert alert-<%= message_type %>"><%= message %></div> -->
    <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
    <% end %>
    <%= yield %>
    <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/posts/_post.html.erb
<li id="post-<%= post.id %>">
  <%= link_to gravatar_for(post.user, size: 50), post.user %>
  <span class="user"><%= link_to post.user.name, post.user %></span>
  <span class="content">
  <%= post.content %></span>
  <span class="timestamp">
    投稿日 <%= time_ago_in_words(post.created_at) %> 前
    <% if current_page?(post.user) %>
      <%= link_to "delete", post, method: :delete,
                                       data: { confirm: "この投稿を削除します。" } %>
    <% end %>
  </span>
</li>

app/views/posts/index.html.erb
<div class="d-flex align-items-center">
    <h1>投稿一覧</h1>
    <div class="ml-auto posts_button">
        <a class="btn btn-outline-info" href="/posts/new" role="button">投稿</a>
    </div>
</div>
<table class="table table-bordered border-light table-hover table-sm posts_table">
  <thead class="thead-dark">
    <tr>
      <th scope="col" style="width: 40px">No.</th>
      <th scope="col-sm-4 col-md-6">投稿タイトル</th>
      <th scope="col">投稿者</th>
      <th scope="col">投稿日</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th scope="row">1</th>
      <td>Test1</td>
      <td>hoge</td>
      <td>2018/4/1</td>
    </tr>
    <tr>
      <th scope="row">2</th>
      <td>Test1</td>
      <td>hoge</td>
      <td>2018/4/1</td>
    </tr>
    <tr>
      <th scope="row">3</th>
      <td>Test1</td>
      <td>hoge</td>
      <td>2018/4/1</td>
    </tr>
  </tbody>
</table>

app/views/posts/new.html.erb
<div class="d-flex align-items-center">
  <h1>投稿</h1>
  <div class="ml-auto posts_button">
      <a class="btn btn-outline-info" href="/posts">投稿一覧</a>
  </div>
</div>
<%=  form_with(model: @post, local: true) do |f| %>
    <div class="form-group">
        <%= f.label :name, '投稿者名' %>
        <%= f.text_field :name, class: 'form-control' %>
        <small id="poster-tip" class="form-text text-muted">
            あなたの名前を入力してください。
        </small>
    </div>
    <div class="form-group">
        <%= f.label :content, '投稿内容' %>
        <%= f.text_area :content, class: 'form-control', rows:10 %>
        <small id="content-tip" class="form-text text-muted">
            投稿内容を入力してください。
        </small>
    </div>
    <div class="form-group">
     <%= f.label :画像 %><br />
    <%= f.file_field :image, class: "image" %>
    <p><%= f.check_box :remove_image %>画像を削除する</p>
    </div>
    <%= f.submit '投稿', class: 'btn btn-info btn-block' %>
    <small id="submit-tip" class="form-text text-muted">
        投稿する前に投稿内容を見直してください!
    </small>
<% end %>

app/views/posts/show.html.erb
<p>
  <strong>Text:</strong>
  <%= @post.text %>
</p>
<p>
  <strong>Image:</strong>
  <%= image_tag @post.image.url　if @post.image? %>
</p>

app/views/shared/_comment.html.erb
<% if @comment_items.any? %>
  <ol class="posts">
    <%= render @comment_items %>
  </ol>
  <%= will_paginate @comment_items %>
<% end %>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation" class="alert alert-danger">
    <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_post_form.html.erb
<%= form_with(model: @post, local: true) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
    <%= f.text_area :content, placeholder: "何か投稿してみてください" %>
  </div>
  <%= f.submit "投稿する", class: "btn btn-primary" %>
<% end %>

app/views/shared/_user_info.html.erb
<%= link_to gravatar_for(current_user, size: 50), current_user %>
<h1><%= current_user.name %></h1>
<span><%= link_to "プロフィールへ", current_user %></span>
<span><%= pluralize(current_user.posts.count, "投稿数") %></span>

app/views/static_pages/about.html.erb
<div class="center jumbotron">
<%= image_tag 'logo.png', :size => '450x300' %></div>
<div class="text-center">
  <h1>About</h1>
  <p>
    railstutorial第6版や、他のサイトを参照に制作した
  <br>
    記事投稿サイトです。
  </p>
</div>

app/views/static_pages/home.html.erb
<% if logged_in? %>
  <div class="row">
    <aside class="col-md-4">
      <section class="user_info">
        <%= render 'shared/user_info' %>
      </section>
      <section class="post_form">
        <%= render 'shared/post_form' %>
      </section>
    </aside>
    <div class="col-md-8">
      <h3>投稿</h3>
      <%= render 'shared/comment' %>
    </div>
  </div>
<% else %>  <div class="center jumbotron">
    <%= image_tag 'logo.png', :size => '450x300' %>
  </div>
  <h1 class="text-center">ようこそstarsへ</h1>
  <div class="col text-center">
    <%= link_to "新規登録", signup_path, class: "btn btn-lg btn-primary" %>
  </div>
  <% end %>

app/views/users/_user.html.erb
<li>
  <%= gravatar_for user, size: 50 %>
  <%= link_to user.name, user %>
  <% if current_user.admin? && !current_user?(user) %>
    | <%= link_to "delete", user, method: :delete,
                                  data: { confirm: "You sure?" } %>
  <% end %>
</li>

app/views/users/edit.html.erb
<h1 class="text-center">ユーザー編集</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_with(model: @user, local: true) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :name, "名前" %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email, "メールアドレス" %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password, "パスワード" %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "変更するパスワードの再入力" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "更新", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<div class="text-center">
<h1>ユーザー一覧</h1>

<%= will_paginate %>

<ul class="users_index">
  <% @users.each do |user| %>
    <li>
      <%= gravatar_for user, size: 70%>
      <%= link_to user.name, user %>
    </li>
  <% end %>
</ul>

<%= will_paginate %>
</div>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<div class="text-center">
  <h1>新規登録</h1>
</div>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_with(model: @user, local: true) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control'  %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control'  %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control'  %>

      <%= f.label :password_confirmation, "新しいパスワードの再入力" %>
      <%= f.password_field :password_confirmation, class: 'form-control'  %>

      <%= f.submit "アカウント作成", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="col-md-3">
    <section class="user_info">
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
    </section>
  </aside>
  <div class="col-md-8">
    <% if @user.posts.any? %>
      <h3>投稿 (<%= @user.posts.count %>)</h3>
      <ol class="posts">
        <%= render @posts %>
      </ol>
      <%= will_paginate @posts %>
    <% end %>
  </div>
</div>